name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (If Needed)
        run: npm install  # Remove if it's a plain HTML/CSS project

      - name: Build Project (If Needed)
        run: npm run build  # Remove if it's a plain HTML/CSS project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Change to your output directory
